Description:  This template deploys an S3 bucket for storage of recipes.

Parameters:
  KMSKey:
    Type: String
    Default: "arn:aws:kms:us-east-1:032796414879:key/0a7ddc47-ecc2-45a7-bfdb-06a57513102b"

Resources:
  S3BucketRecipesFree:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ "-", [ "cand-c3-free-recipes", !Ref 'AWS::AccountId' ] ]
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Ref KMSKey
  S3BucketRecipesSecret:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ "-", [ "cand-c3-secret-recipes", !Ref 'AWS::AccountId' ] ]
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Ref KMSKey
  S3BucketVPCFlowLogs:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Join [ "-", [ "cand-c3-vpc-flow-logs", !Ref 'AWS::AccountId' ] ]
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: aws:kms
                KMSMasterKeyID: !Ref KMSKey

Outputs:
  BucketNameRecipesFree:
    Value: !Ref 'S3BucketRecipesFree'
    Description: Name of the Amazon S3 bucket that you will upload free recipes to.
    Export:
      Name: BucketNameRecipesFree
  BucketNameRecipesSecret:
    Value: !Ref 'S3BucketRecipesSecret'
    Description: Name of the Amazon S3 bucket that you will upload secret recipes to.
    Export:
      Name: BucketNameRecipesSecret
  BucketArnVPCFlowLogs:
    Value: !GetAtt S3BucketVPCFlowLogs.Arn
    Description: Arn of the Amazon S3 bucket that have vpc flow logs for this project
    Export:
      Name: BucketArnVPCFlowLogs
